### ISSUE TITLE
try to build your first ML model on the dataset

### ISSUE THREAD

**Issue by philippabele** [philippabele/angular-contact-with-pytorch#19]
We are now at the point where the creative part starts. I would like to survey two scenarios:

- Use force and speed as inputs and determine the lifetime.
- Use lifetime and speed as inputs and determine the speed.

The way of modelling the challenge is free at this point, but I would recommend one which is familiar to your previous work or something you found in the tutorials. For example, are you familiar with categorization? To tune the task in this direction, just decide that you will categorize the results into certain lifetime windows.

**Comment by zanfee** [comment]
A categorization model seems like an interesting idea. Initially I thought about a regression model in order to estimate the value more accurately (not linear regression but one that would fit for exponential functions too).

One way to select the bins for the categorization model would be by using a logarithmic function due to the wide range and exponential nature of the Lifetime. Depending on what else you have planed for this project, it could also be interesting to implement both models (categorization and regression) and compare them to each other based on the actual formula for Lifetime. I don't have much experience with either model though as this is my first ML project.
